---
output: 
  pdf_document:
    latex_engine: xelatex
header-includes:
 -\usepackage{ctex}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

# 1 实验

## 1.1 概述

在科学与工程领域, 一项重要工作是构建系统输入与输出之间的关联关系. 我们所研究的 "系统" 范畴十分广泛, 可以是火箭发动机、机械加工流程, 甚至是人类大脑. 以机械加工流程为例, 输入参数可以是加工转速、刀具切削角度等, 而输出结果则可能是刀具承受的作用力、工件表面温度等.

构建这种输入输出关联关系 (也被称为响应面) 的一种方式, 是采集系统运行数据, 并借助统计学与机器学习方法推导对应关系. 当数据获取成本高昂、资源条件有限时, 就必须合理规划数据采集工作, 力求以最低的成本和最短的时间获取有效数据. 针对系统开展周密设计的实验, 便是实现这一目标的有效手段.

本文中所提及的实验, 是指主动对输入参数进行定向调整并观测输出结果, 这与观测性研究存在本质区别: 观测性研究仅单纯记录系统的输入与输出, 不会对系统本身做出任何人为改动. 而实验设计, 就是开展这类实验的整套方案, 明确了数据的采集位置与采集方式.

构建输入输出关联关系的另一种思路, 是依托支配系统运行的物理定律 (如牛顿定律) 推导对应关系. 有人可能会认为, 采用这种方法就不再需要数据和实验, 但事实并非如此. 基于物理原理搭建的模型中往往包含未知常数 (例如摩擦系数) , 这类参数必须依靠实际系统的采集数据才能确定. 除此之外, 物理模型通常难以整理为便于计算的解析函数, 往往需要借助复杂的数值方法求解其对应的数学模型——比如求解偏微分方程组时会用到有限元法. 将求解流程在计算机中通过代码实现后, 得到的程序一般被称作计算机模型或仿真器.

由于计算机模型的运算开销极大, 针对其开展的计算机实验同样需要精心规划. 因此, 实验设计在此类场景中依旧至关重要, 区别仅在于无需关注实验的具体操作方式, 只需确定实验的取样位置即可.

在部分场景下, 需要结合上述两种方法, 才能完整搭建出系统的输入输出关联关系. 举例来说, 研究人员若无法完全吃透系统原理, 搭建出的物理模型便会存在一定偏差. 这种情况十分普遍, 绝大多数工程系统与生物系统结构复杂, 很难单纯依靠物理规律完成全维度建模. 因此, 研究人员仍需采集实际系统的数据, 修正因物理机理缺失造成的模型偏差, 并对计算机模型进行参数校准. 这一过程, 既需要开展实体物理实验, 也离不开计算机仿真实验.
